### ISSUE TITLE
lightgbm.basic.LightGBMError: Label 1330 is not less than the number of label mappings (31)

### ISSUE THREAD

**Issue by gallupliu** [wildltr/ptranking#9]
When I executed the program with the following command, python -data MQ2008_List -dir_data /Users/gallup/study/tensorflow-LTR/data/MQ2008/Fold1 -dir_output /home/dl-box/WorkBench/CodeBench/Project_output/Out_L2R/Listwise/ -model LightGBMLambdaMART -dir_json /Users/gallup/study/ptranking/testing/ltr_tree/json/

I encountered an error：
lightgbm.basic.LightGBMError: Label 1330 is not less than the number of label mappings (31)

Start LightGBMLambdaMART on MQ2008_List >>>
Fold- 1
/Users/gallup/opt/anaconda3/envs/tf2py3/lib/python3.8/site-packages/lightgbm/engine.py:151: UserWarning: Found `num_trees` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Fatal] Label 1330 is not less than the number of label mappings (31)
Traceback (most recent call last):
  File "/Users/gallup/study/ptranking/pt_ranking.py", line 85, in <module>
    evaluator.run(model_id=l2r_args.model, dir_json=l2r_args.dir_json, debug=False, config_with_json=True)
  File "/Users/gallup/study/ptranking/ptranking/ltr_adhoc/eval/ltr.py", line 604, in run
    self.grid_run(debug=debug, model_id=model_id, dir_json=dir_json)
  File "/Users/gallup/study/ptranking/ptranking/ltr_tree/eval/ltr_tree.py", line 380, in grid_run
    self.kfold_cv_eval(data_dict=data_dict, eval_dict=eval_dict, model_para_dict=model_para_dict)
  File "/Users/gallup/study/ptranking/ptranking/ltr_tree/eval/ltr_tree.py", line 257, in kfold_cv_eval
    y_test, group_test, y_pred = tree_ranker.run(fold_k=fold_k, file_train=file_train, file_vali=file_vali,
  File "/Users/gallup/study/ptranking/ptranking/ltr_tree/lambdamart/lightgbm_lambdaMART.py", line 109, in run
    lgbm_ranker = lgbm.train(params=self.lightgbm_para_dict, verbose_eval=10,
  File "/Users/gallup/opt/anaconda3/envs/tf2py3/lib/python3.8/site-packages/lightgbm/engine.py", line 231, in train
    booster = Booster(params=params, train_set=train_set)
  File "/Users/gallup/opt/anaconda3/envs/tf2py3/lib/python3.8/site-packages/lightgbm/basic.py", line 1988, in __init__
    _safe_call(_LIB.LGBM_BoosterCreate(
  File "/Users/gallup/opt/anaconda3/envs/tf2py3/lib/python3.8/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Label 1330 is not less than the number of label mappings (31)

Process finished with exit code 1

**Comment by ii-research-yu** [comment]
@gallupliu Sorry for the inconvenience. The possible reason is that the dataset MQ2008-List is a listwise dataset rather than the common multi-graded labels, say {0,1,2,3}. Since  LightGBMLambdaMART builds on LightGBM, it is probably because LightGBM does not support this kind of dataset. Please double-check it, thanks!

**Comment by gallupliu** [comment]
I use the mq2008 ，label as （0 1 2）

**Comment by laurel2935** [comment]
@gallupliu Hi, for other datasets, it should work, can you show me how you run the code, and the setting? thanks!
